### ISSUE TITLE
build遇错

### ISSUE THREAD

**Issue by briteming** [earthengine/rocks#1]
hi.

在我的vps上。
[root@host rocks-by-earthengine]# cargo  build --release
显示：
...
Compiling trust-dns-proto v0.7.4
   Compiling futures-preview v0.3.0-alpha.17
   Compiling tokio v0.1.22
   Compiling tokio v0.2.0 (https://github.com/tokio-rs/tokio#79b017c7)
   Compiling trust-dns-resolver v0.11.1
   Compiling rocks v0.1.0 (/root/rocks-by-earthengine)
error: incorrect use of `await`
  --> src/connection.rs:43:20
   |
43 |     let (r1, r2) = await!(join(i2o, o2i,));
   |                    ^^^^^^^^^^^^^^^^^^^^^^^ help: `await` is a postfix operation: `join(i2o, o2i,).await`

error: incorrect use of `await`
  --> src/socks5/incoming.rs:72:15
   |
72 |         match await!(outgoing.clone().process_request(req.clone())) {
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: `await` is a postfix operation: `outgoing.clone().process_request(req.clone()).await`

error[E0557]: feature has been removed
 --> src/main.rs:2:5
  |
2 |     await_macro,
  |     ^^^^^^^^^^^ feature has been removed
  |
  = note: subsumed by `.await` syntax

error: future cannot be sent between threads safely
   --> src/socks5/incoming.rs:49:13
    |
49  |             tokio::spawn( {
    |             ^^^^^^^^^^^^ future is not `Send`
    | 
   ::: /root/.cargo/git/checkouts/tokio-377c595163f99a10/79b017c/tokio/src/executor.rs:104:40
    |
104 |     F: Future<Output = ()> + 'static + Send,
    |                                        ---- required by this bound in `tokio::executor::spawn`
    |
    = help: the trait `std::marker::Sync` is not implemented for `O`
help: consider further restricting this bound with `+ std::marker::Sync`
   --> src/socks5/incoming.rs:36:9
    |
36  |         O: Outgoing + Send + 'static
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: future is not `Send` as this value is used across an await
   --> src/socks5/incoming.rs:85:58
    |
72  |         match await!(outgoing.clone().process_request(req.clone())) {
    |                      -------- has type `&O`
...
85  |                 self.send_final_response(self.get_reason(&e), req).await?;
    |                                                          ^^ await occurs here, with `outgoing` maybe used later
...
88  |         };
    |          - `outgoing` is later dropped here
help: consider moving this into a `let` binding to create a shorter lived borrow
   --> src/socks5/incoming.rs:72:22
    |
72  |         match await!(outgoing.clone().process_request(req.clone())) {
    |                      ^^^^^^^^^^^^^^^^

error: aborting due to 4 previous errors

For more information about this error, try `rustc --explain E0557`.
error: could not compile `rocks`.

To learn more, run the command again with --verbose.
[root@104 rocks-by-earthengine]#

如何解决？

**Comment by earthengine** [comment]
This project has been released before Rust supports `await`, and requires a major upgrade.

Please wait for the next release.

**Comment by briteming** [comment]
如果发布了新的release,请在此通知。
谢谢

**Comment by earthengine** [comment]
此項目已更新，請參照Readme.md説明。

**Comment by briteming** [comment]
hi.

这次在vps上build成功，生成了可执行文件rocks.
但是在 Mac上，
我设置了 git的代理：
git config --global http.proxy 'socks5://127.0.0.1:8766'
git config --global https.proxy 'socks5://127.0.0.1:8766'

也设置了cargo的代理：
nano ~/.cargo/config
cat ~/.cargo/config
显示：
[http]
proxy = 'socks5://127.0.0.1:8766'
[https]
proxy = 'socks5://127.0.0.1:8766'

但是运行  cargo build --release遇错：
yudeMacBook-Air:rocks-by-earthengine ym$ cargo build --release
    Updating crates.io index
warning: spurious network error (2 tries remaining): [7] Couldn't connect to server (Failed to receive SOCKS5 connect request ack.); class=Net (12)

warning: spurious network error (1 tries remaining): [7] Couldn't connect to server (Failed to receive SOCKS5 connect request ack.); class=Net (12)
error: failed to get `clap` as a dependency of package `rocks v0.1.0 (/Users/ym/rocks-by-earthengine)`

Caused by:
  failed to load source for dependency `clap`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to fetch `https://github.com/rust-lang/crates.io-index`

Caused by:
  network failure seems to have happened
  if a proxy or similar is necessary `net.git-fetch-with-cli` may help here
  https://doc.rust-lang.org/cargo/reference/config.html#netgit-fetch-with-cli

Caused by:
  [7] Couldn't connect to server (Failed to receive SOCKS5 connect request ack.); class=Net (12)
yudeMacBook-Air:rocks-by-earthengine ym$

不知在哪里搞错了？
谢谢你的回复

**Comment by briteming** [comment]
这里socks5://127.0.0.1:8766 是我在本地机器上运行的一个 socks proxy, 给浏览器设置socks proxy地址后，浏览器是可以成功翻墙的。

**Comment by briteming** [comment]
能提供mac上的可执行文件下载吗

**Comment by earthengine** [comment]
這個似乎與Mac無關，是Cargo系統不能翻墻導致 - 如果“Updating crate.io"失敗，那是本項目代碼都還沒有讀取，就失敗了。請向Cargo提交Issue。

**Comment by earthengine** [comment]
我目前沒有Mac開發機器可用，因此無法生成Mac可執行文件。
也許你可以試試[Docker-OSX](https://github.com/sickcodes/Docker-OSX) ，看能不能在VPS上跑一個Docker的OSX, 然後在上面Build。我沒用過不知道是否可行。

**Comment by earthengine** [comment]
本Issue已解決。有進一步的問題請開新Issue，謝謝。

**Comment by briteming** [comment]
hi.
在 Mac上，我另外搞了个http proxy 127.0.0.1:8788
我设置了 git的代理：
git config --global http.proxy 'http://127.0.0.1:8788'
git config --global https.proxy 'http://127.0.0.1:8788'

也设置了cargo的代理：
nano ~/.cargo/config
cat ~/.cargo/config
显示：
[http]
proxy = 'http://127.0.0.1:8788'
[https]
proxy = 'http://127.0.0.1:8788'

运行 cargo build --release就不会遇错了。不过运行此命令后，要等15分钟才会有输出。

**Comment by briteming** [comment]
不过你说“Can run as a local SOCKS5 proxy, and use Rocks protocol to connect to the remote proxy“-现在还不可用。
何时正式实现了‘Can run as a local SOCKS5 proxy, and use Rocks protocol to connect to the remote proxy’，请在此通知一下。
